version: "3"
services:
#   rabbitmq:
#     image: "rabbitmq:3-management"
#     ports:
#       - "5672:5672"
#       - "15672:15672"


  flask_server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - ./deploy:/app/deploy
    ports:
      - "5001:80"
    env_file:
    - path: ./.env.docker.rc
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "200M"
