"""make name not unique

Revision ID: 7a07661c9453
Revises: 1bf3dd04d67f
Create Date: 2025-02-15 11:29:53.833146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a07661c9453'
down_revision: Union[str, None] = '1bf3dd04d67f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('test_users_name_key', 'test_users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('test_users_name_key', 'test_users', ['name'])
    # ### end Alembic commands ###
